version: '3'
services:
  auth-app:
    build:
      context: auth-app
      dockerfile: Dockerfile.development
    image: vitality/auth-app
    container_name: auth-app
    ports:
      - "3337:1337"
    links:
      - "mongo"
    depends_on:
      - "mongo"
    volumes:
      - ./auth-app:/app
      - auth-app-node-modules:/app/node_modules
  api-app:
      build:
        context: api-app
        dockerfile: Dockerfile.development
      image: vitality/api-app
      container_name: api-app
      ports:
        - "3338:1337"
      links:
        - "mongo"
      depends_on:
        - "mongo"
      volumes:
        - ./api-app:/app
        - api-app-node-modules:/app/node_modules
  client-app:
        build:
          context: client-app
          dockerfile: Dockerfile.development
        image: vitality/client-app
        container_name: client-app
        ports:
          - "3000:3000"
        volumes:
          - ./client-app:/app
          - client-app-node-modules:/app/node_modules
        links:
          - "auth-app"
          - "api-app"
        depends_on:
          - "auth-app"
          - "api-app"
  mongo:
    image: "mongo"
    ports:
      - 27018:27017
    volumes:
      - mongo-storage:/data/db

volumes:
  mongo-storage:
  client-app-node-modules:
  auth-app-node-modules:
  api-app-node-modules:


